### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by MagpieMcGraw** [vassvik/odin-glfw#4]
I downloaded odin-glfw and succesfully imported it into my program, but it doesn't compile. 
Now I notice that I'm using Odin 0.8.0-dev, and the latest official release is 0.71. Could that be the cause?

Here are the lines which don't compile:
![screenshot at 2018-01-26 19-54-39](https://user-images.githubusercontent.com/17641521/35453438-de796f74-02d2-11e8-8175-9fbb5a279420.png)

**Comment by vassvik** [comment]
Hi there! It looks like you're either on an old commit of Odin (that doesn't have named procedure arguments) or an old commit of this repository (that is not updated to account for the syntax change to named arguments).. The errors you are getting is due to changes to named procedure arguments that was made a little more than a week ago. In particular, named return arguments are now pre-declared, which this library now reflects.

The latest commit of odin-glfw is `4ea6fb0cb998c8aa0c357938b4f2019f247ef306` from the 18th of January.

**Comment by MagpieMcGraw** [comment]
Thanks, I updated and now everything is good!

**Comment by vassvik** [comment]
Excellent!
